### ISSUE TITLE
Уничтожение объектов

### ISSUE THREAD

**Issue by Red-Cat-Fat** [VitSun666/UnityFruitNinjaClone#1]
Пусть slices сам себя уничтожит после спавна
https://github.com/VitSun666/UnityFruitNinjaClone/blob/055e5043f0fa92c3a58efadb690ef299dc60bf9f/UnityFruitNinjaClone/Assets/Scripts/Fruit.cs#L27

**Comment by VitSun666** [comment]
Сделал спавн и уничтожение в одну строку, не заводя дополнительных переменных. Если я вас правильно понял. b807b3b5ec25e291e0b838f397bc7e3d51589c21

**Comment by Red-Cat-Fat** [comment]
Нет, ты понял не правильно. Ты спавнишь объект, а потом их того же места их удаляешь. 
Логика смерти объекта должна быть в самом объекте.

**Comment by VitSun666** [comment]
Теперь вроде как понял, создал скрипт для префаба и прикрепил к нему. Хоть оценку уже и выставили, можете посмотреть, сделал ли я правильно? https://github.com/VitSun666/UnityFruitNinjaClone/commit/b9181a66ea1dc8c4c1955d08a18ec8840ed0ed51

**Comment by Red-Cat-Fat** [comment]
Отлично! Сделал почти правильно - дай дизайнерам самим настраивать тайминги уничтожения - они тебя за это поблагодарят. Добавь сериализуемую переменную, отвечающую за общение с движком Unity и будет прям отлично
